### ISSUE TITLE
Link from 3b1b's "Bayes theorem" video has broken

### ISSUE THREAD

**Issue by shun-liang** [nskobelevs/nskobelevs.github.io#1]
Hi, thanks for the great demo. And it is great to see the demo is featured in the description 3b1b's Bayes Theorem [video](https://www.youtube.com/watch?v=HZGCoVF3YvM).

In the 3b1b's video, there is a link to the old URL of the demo:
> Interactive made by Reddit user Thoggalluth: https://nskobelevs.github.io/p5js/Bay...

And after [this commit](https://github.com/nskobelevs/nskobelevs.github.io/commit/e7b82aa9989698b724f5388eb528a8a39962af00), that URL is no longer valid.

Would you kindly consider redirecting the old URL to the [new one](https://nskobelevs.github.io/BayesTheorem/), to avoid many 3b1b viewers being confused? Many thanks.

**Comment by nskobelevs** [comment]
Thank for letting me know! I was refactoring and the link had left my mind. I'll move it back into the p5js folder, temporarily. 
I'll see if I can get in touch with 3Blue1Brown to change the link as I'd like to move the sketch to my skobelevs.ie repo which will become my portfolio

Fixed in most recent commits!
